// Holidays
Meteor.startup(() => {
  if (Holidays.find().count() === 0) {




    [
      {
        "date":"01/01/01",
        "name":"Confrat Univ"
      },
      {
        "date":"02/26/01",
        "name":"Carnaval"
      },
      {
        "date":"02/27/01",
        "name":"Carnaval"
      },
      {
        "date":"04/13/01",
        "name":"Páscoa"
      },
      {
        "date":"04/21/01",
        "name":"Tiradentes"
      },
      {
        "date":"05/01/01",
        "name":"Dia do Trabalho"
      },
      {
        "date":"06/14/01",
        "name":"Corpus Christi"
      },
      {
        "date":"09/07/01",
        "name":"Independencia"
      },
      {
        "date":"10/12/01",
        "name":"Nossa Sr.a Aparecida"
      },
      {
        "date":"11/02/01",
        "name":"Finados"
      },
      {
        "date":"11/15/01",
        "name":"Republica"
      },
      {
        "date":"12/25/01",
        "name":"Natal"
      },
      {
        "date":"01/01/02",
        "name":"Confrat Univ"
      },
      {
        "date":"02/11/02",
        "name":"Carnaval"
      },
      {
        "date":"02/12/02",
        "name":"Carnaval"
      },
      {
        "date":"03/29/02",
        "name":"Páscoa"
      },
      {
        "date":"04/21/02",
        "name":"Tiradentes"
      },
      {
        "date":"05/01/02",
        "name":"Dia do Trabalho"
      },
      {
        "date":"05/30/02",
        "name":"Corpus Christi"
      },
      {
        "date":"09/07/02",
        "name":"Independencia"
      },
      {
        "date":"10/12/02",
        "name":"Nossa Sr.a Aparecida"
      },
      {
        "date":"11/02/02",
        "name":"Finados"
      },
      {
        "date":"11/15/02",
        "name":"Republica"
      },
      {
        "date":"12/25/02",
        "name":"Natal"
      },
      {
        "date":"01/01/03",
        "name":"Confrat Univ"
      },
      {
        "date":"03/03/03",
        "name":"Carnaval"
      },
      {
        "date":"03/04/03",
        "name":"Carnaval"
      },
      {
        "date":"04/18/03",
        "name":"Páscoa"
      },
      {
        "date":"04/21/03",
        "name":"Tiradentes"
      },
      {
        "date":"05/01/03",
        "name":"Dia do Trabalho"
      },
      {
        "date":"06/19/03",
        "name":"Corpus Christi"
      },
      {
        "date":"09/07/03",
        "name":"Independencia"
      },
      {
        "date":"10/12/03",
        "name":"Nossa Sr.a Aparecida"
      },
      {
        "date":"11/02/03",
        "name":"Finados"
      },
      {
        "date":"11/15/03",
        "name":"Republica"
      },
      {
        "date":"12/25/03",
        "name":"Natal"
      },
      {
        "date":"01/01/04",
        "name":"Confrat Univ"
      },
      {
        "date":"02/23/04",
        "name":"Carnaval"
      },
      {
        "date":"02/24/04",
        "name":"Carnaval"
      },
      {
        "date":"04/09/04",
        "name":"Páscoa"
      },
      {
        "date":"04/21/04",
        "name":"Tiradentes"
      },
      {
        "date":"05/01/04",
        "name":"Dia do Trabalho"
      },
      {
        "date":"06/10/04",
        "name":"Corpus Christi"
      },
      {
        "date":"09/07/04",
        "name":"Independencia"
      },
      {
        "date":"10/12/04",
        "name":"Nossa Sr.a Aparecida"
      },
      {
        "date":"11/02/04",
        "name":"Finados"
      },
      {
        "date":"11/15/04",
        "name":"Republica"
      },
      {
        "date":"12/25/04",
        "name":"Natal"
      },
      {
        "date":"01/01/05",
        "name":"Confrat Univ"
      },
      {
        "date":"02/07/05",
        "name":"Carnaval"
      },
      {
        "date":"02/08/05",
        "name":"Carnaval"
      },
      {
        "date":"03/25/05",
        "name":"Páscoa"
      },
      {
        "date":"04/21/05",
        "name":"Tiradentes"
      },
      {
        "date":"05/01/05",
        "name":"Dia do Trabalho"
      },
      {
        "date":"05/26/05",
        "name":"Corpus Christi"
      },
      {
        "date":"09/07/05",
        "name":"Independencia"
      },
      {
        "date":"10/12/05",
        "name":"Nossa Sr.a Aparecida"
      },
      {
        "date":"11/02/05",
        "name":"Finados"
      },
      {
        "date":"11/15/05",
        "name":"Republica"
      },
      {
        "date":"12/25/05",
        "name":"Natal"
      },
      {
        "date":"01/01/06",
        "name":"Confrat Univ"
      },
      {
        "date":"02/27/06",
        "name":"Carnaval"
      },
      {
        "date":"02/28/06",
        "name":"Carnaval"
      },
      {
        "date":"04/14/06",
        "name":"Páscoa"
      },
      {
        "date":"04/21/06",
        "name":"Tiradentes"
      },
      {
        "date":"05/01/06",
        "name":"Dia do Trabalho"
      },
      {
        "date":"06/15/06",
        "name":"Corpus Christi"
      },
      {
        "date":"09/07/06",
        "name":"Independencia"
      },
      {
        "date":"10/12/06",
        "name":"Nossa Sr.a Aparecida"
      },
      {
        "date":"11/02/06",
        "name":"Finados"
      },
      {
        "date":"11/15/06",
        "name":"Republica"
      },
      {
        "date":"12/25/06",
        "name":"Natal"
      },
      {
        "date":"01/01/07",
        "name":"Confrat Univ"
      },
      {
        "date":"02/19/07",
        "name":"Carnaval"
      },
      {
        "date":"02/20/07",
        "name":"Carnaval"
      },
      {
        "date":"04/06/07",
        "name":"Páscoa"
      },
      {
        "date":"04/21/07",
        "name":"Tiradentes"
      },
      {
        "date":"05/01/07",
        "name":"Dia do Trabalho"
      },
      {
        "date":"06/07/07",
        "name":"Corpus Christi"
      },
      {
        "date":"09/07/07",
        "name":"Independencia"
      },
      {
        "date":"10/12/07",
        "name":"Nossa Sr.a Aparecida"
      },
      {
        "date":"11/02/07",
        "name":"Finados"
      },
      {
        "date":"11/15/07",
        "name":"Republica"
      },
      {
        "date":"12/25/07",
        "name":"Natal"
      },
      {
        "date":"01/01/08",
        "name":"Confrat Univ"
      },
      {
        "date":"02/04/08",
        "name":"Carnaval"
      },
      {
        "date":"02/05/08",
        "name":"Carnaval"
      },
      {
        "date":"03/21/08",
        "name":"Páscoa"
      },
      {
        "date":"04/21/08",
        "name":"Tiradentes"
      },
      {
        "date":"05/01/08",
        "name":"Dia do Trabalho"
      },
      {
        "date":"05/22/08",
        "name":"Corpus Christi"
      },
      {
        "date":"09/07/08",
        "name":"Independencia"
      },
      {
        "date":"10/12/08",
        "name":"Nossa Sr.a Aparecida"
      },
      {
        "date":"11/02/08",
        "name":"Finados"
      },
      {
        "date":"11/15/08",
        "name":"Republica"
      },
      {
        "date":"12/25/08",
        "name":"Natal"
      },
      {
        "date":"01/01/09",
        "name":"Confrat Univ"
      },
      {
        "date":"02/23/09",
        "name":"Carnaval"
      },
      {
        "date":"02/24/09",
        "name":"Carnaval"
      },
      {
        "date":"04/10/09",
        "name":"Páscoa"
      },
      {
        "date":"04/21/09",
        "name":"Tiradentes"
      },
      {
        "date":"05/01/09",
        "name":"Dia do Trabalho"
      },
      {
        "date":"06/11/09",
        "name":"Corpus Christi"
      },
      {
        "date":"09/07/09",
        "name":"Independencia"
      },
      {
        "date":"10/12/09",
        "name":"Nossa Sr.a Aparecida"
      },
      {
        "date":"11/02/09",
        "name":"Finados"
      },
      {
        "date":"11/15/09",
        "name":"Republica"
      },
      {
        "date":"12/25/09",
        "name":"Natal"
      },
      {
        "date":"01/01/10",
        "name":"Confrat Univ"
      },
      {
        "date":"02/15/10",
        "name":"Carnaval"
      },
      {
        "date":"02/16/10",
        "name":"Carnaval"
      },
      {
        "date":"04/02/10",
        "name":"Páscoa"
      },
      {
        "date":"04/21/10",
        "name":"Tiradentes"
      },
      {
        "date":"05/01/10",
        "name":"Dia do Trabalho"
      },
      {
        "date":"06/03/10",
        "name":"Corpus Christi"
      },
      {
        "date":"09/07/10",
        "name":"Independencia"
      },
      {
        "date":"10/12/10",
        "name":"Nossa Sr.a Aparecida"
      },
      {
        "date":"11/02/10",
        "name":"Finados"
      },
      {
        "date":"11/15/10",
        "name":"Republica"
      },
      {
        "date":"12/25/10",
        "name":"Natal"
      },
      {
        "date":"01/01/11",
        "name":"Confrat Univ"
      },
      {
        "date":"03/07/11",
        "name":"Carnaval"
      },
      {
        "date":"03/08/11",
        "name":"Carnaval"
      },
      {
        "date":"04/21/11",
        "name":"Páscoa"
      },
      {
        "date":"04/22/11",
        "name":"Tiradentes"
      },
      {
        "date":"05/01/11",
        "name":"Dia do Trabalho"
      },
      {
        "date":"06/23/11",
        "name":"Corpus Christi"
      },
      {
        "date":"09/07/11",
        "name":"Independencia"
      },
      {
        "date":"10/12/11",
        "name":"Nossa Sr.a Aparecida"
      },
      {
        "date":"11/02/11",
        "name":"Finados"
      },
      {
        "date":"11/15/11",
        "name":"Republica"
      },
      {
        "date":"12/25/11",
        "name":"Natal"
      },
      {
        "date":"01/01/12",
        "name":"Confrat Univ"
      },
      {
        "date":"02/20/12",
        "name":"Carnaval"
      },
      {
        "date":"02/21/12",
        "name":"Carnaval"
      },
      {
        "date":"04/06/12",
        "name":"Páscoa"
      },
      {
        "date":"04/21/12",
        "name":"Tiradentes"
      },
      {
        "date":"05/01/12",
        "name":"Dia do Trabalho"
      },
      {
        "date":"06/07/12",
        "name":"Corpus Christi"
      },
      {
        "date":"09/07/12",
        "name":"Independencia"
      },
      {
        "date":"10/12/12",
        "name":"Nossa Sr.a Aparecida"
      },
      {
        "date":"11/02/12",
        "name":"Finados"
      },
      {
        "date":"11/15/12",
        "name":"Republica"
      },
      {
        "date":"12/25/12",
        "name":"Natal"
      },
      {
        "date":"01/01/13",
        "name":"Confrat Univ"
      },
      {
        "date":"02/11/13",
        "name":"Carnaval"
      },
      {
        "date":"02/12/13",
        "name":"Carnaval"
      },
      {
        "date":"03/29/13",
        "name":"Páscoa"
      },
      {
        "date":"04/21/13",
        "name":"Tiradentes"
      },
      {
        "date":"05/01/13",
        "name":"Dia do Trabalho"
      },
      {
        "date":"05/30/13",
        "name":"Corpus Christi"
      },
      {
        "date":"09/07/13",
        "name":"Independencia"
      },
      {
        "date":"10/12/13",
        "name":"Nossa Sr.a Aparecida"
      },
      {
        "date":"11/02/13",
        "name":"Finados"
      },
      {
        "date":"11/15/13",
        "name":"Republica"
      },
      {
        "date":"12/25/13",
        "name":"Natal"
      },
      {
        "date":"01/01/14",
        "name":"Confrat Univ"
      },
      {
        "date":"03/03/14",
        "name":"Carnaval"
      },
      {
        "date":"03/04/14",
        "name":"Carnaval"
      },
      {
        "date":"04/18/14",
        "name":"Páscoa"
      },
      {
        "date":"04/21/14",
        "name":"Tiradentes"
      },
      {
        "date":"05/01/14",
        "name":"Dia do Trabalho"
      },
      {
        "date":"06/19/14",
        "name":"Corpus Christi"
      },
      {
        "date":"09/07/14",
        "name":"Independencia"
      },
      {
        "date":"10/12/14",
        "name":"Nossa Sr.a Aparecida"
      },
      {
        "date":"11/02/14",
        "name":"Finados"
      },
      {
        "date":"11/15/14",
        "name":"Republica"
      },
      {
        "date":"12/25/14",
        "name":"Natal"
      },
      {
        "date":"01/01/15",
        "name":"Confrat Univ"
      },
      {
        "date":"02/16/15",
        "name":"Carnaval"
      },
      {
        "date":"02/17/15",
        "name":"Carnaval"
      },
      {
        "date":"04/03/15",
        "name":"Páscoa"
      },
      {
        "date":"04/21/15",
        "name":"Tiradentes"
      },
      {
        "date":"05/01/15",
        "name":"Dia do Trabalho"
      },
      {
        "date":"06/04/15",
        "name":"Corpus Christi"
      },
      {
        "date":"09/07/15",
        "name":"Independencia"
      },
      {
        "date":"10/12/15",
        "name":"Nossa Sr.a Aparecida"
      },
      {
        "date":"11/02/15",
        "name":"Finados"
      },
      {
        "date":"11/15/15",
        "name":"Republica"
      },
      {
        "date":"12/25/15",
        "name":"Natal"
      },
      {
        "date":"01/01/16",
        "name":"Confrat Univ"
      },
      {
        "date":"02/08/16",
        "name":"Carnaval"
      },
      {
        "date":"02/09/16",
        "name":"Carnaval"
      },
      {
        "date":"03/25/16",
        "name":"Páscoa"
      },
      {
        "date":"04/21/16",
        "name":"Tiradentes"
      },
      {
        "date":"05/01/16",
        "name":"Dia do Trabalho"
      },
      {
        "date":"05/26/16",
        "name":"Corpus Christi"
      },
      {
        "date":"09/07/16",
        "name":"Independencia"
      },
      {
        "date":"10/12/16",
        "name":"Nossa Sr.a Aparecida"
      },
      {
        "date":"11/02/16",
        "name":"Finados"
      },
      {
        "date":"11/15/16",
        "name":"Republica"
      },
      {
        "date":"12/25/16",
        "name":"Natal"
      },
      {
        "date":"01/01/17",
        "name":"Confrat Univ"
      },
      {
        "date":"02/27/17",
        "name":"Carnaval"
      },
      {
        "date":"02/28/17",
        "name":"Carnaval"
      },
      {
        "date":"04/14/17",
        "name":"Páscoa"
      },
      {
        "date":"04/21/17",
        "name":"Tiradentes"
      },
      {
        "date":"05/01/17",
        "name":"Dia do Trabalho"
      },
      {
        "date":"06/15/17",
        "name":"Corpus Christi"
      },
      {
        "date":"09/07/17",
        "name":"Independencia"
      },
      {
        "date":"10/12/17",
        "name":"Nossa Sr.a Aparecida"
      },
      {
        "date":"11/02/17",
        "name":"Finados"
      },
      {
        "date":"11/15/17",
        "name":"Republica"
      },
      {
        "date":"12/25/17",
        "name":"Natal"
      },
      {
        "date":"01/01/18",
        "name":"Confrat Univ"
      },
      {
        "date":"02/12/18",
        "name":"Carnaval"
      },
      {
        "date":"02/13/18",
        "name":"Carnaval"
      },
      {
        "date":"03/30/18",
        "name":"Páscoa"
      },
      {
        "date":"04/21/18",
        "name":"Tiradentes"
      },
      {
        "date":"05/01/18",
        "name":"Dia do Trabalho"
      },
      {
        "date":"05/31/18",
        "name":"Corpus Christi"
      },
      {
        "date":"09/07/18",
        "name":"Independencia"
      },
      {
        "date":"10/12/18",
        "name":"Nossa Sr.a Aparecida"
      },
      {
        "date":"11/02/18",
        "name":"Finados"
      },
      {
        "date":"11/15/18",
        "name":"Republica"
      },
      {
        "date":"12/25/18",
        "name":"Natal"
      },
      {
        "date":"01/01/19",
        "name":"Confrat Univ"
      },
      {
        "date":"03/04/19",
        "name":"Carnaval"
      },
      {
        "date":"03/05/19",
        "name":"Carnaval"
      },
      {
        "date":"04/19/19",
        "name":"Páscoa"
      },
      {
        "date":"04/21/19",
        "name":"Tiradentes"
      },
      {
        "date":"05/01/19",
        "name":"Dia do Trabalho"
      },
      {
        "date":"06/20/19",
        "name":"Corpus Christi"
      },
      {
        "date":"09/07/19",
        "name":"Independencia"
      },
      {
        "date":"10/12/19",
        "name":"Nossa Sr.a Aparecida"
      },
      {
        "date":"11/02/19",
        "name":"Finados"
      },
      {
        "date":"11/15/19",
        "name":"Republica"
      },
      {
        "date":"12/25/19",
        "name":"Natal"
      },
      {
        "date":"01/01/20",
        "name":"Confrat Univ"
      },
      {
        "date":"02/24/20",
        "name":"Carnaval"
      },
      {
        "date":"02/25/20",
        "name":"Carnaval"
      },
      {
        "date":"04/10/20",
        "name":"Páscoa"
      },
      {
        "date":"04/21/20",
        "name":"Tiradentes"
      },
      {
        "date":"05/01/20",
        "name":"Dia do Trabalho"
      },
      {
        "date":"06/11/20",
        "name":"Corpus Christi"
      },
      {
        "date":"09/07/20",
        "name":"Independencia"
      },
      {
        "date":"10/12/20",
        "name":"Nossa Sr.a Aparecida"
      },
      {
        "date":"11/02/20",
        "name":"Finados"
      },
      {
        "date":"11/15/20",
        "name":"Republica"
      },
      {
        "date":"12/25/20",
        "name":"Natal"
      },
      {
        "date":"01/01/21",
        "name":"Confrat Univ"
      },
      {
        "date":"02/15/21",
        "name":"Carnaval"
      },
      {
        "date":"02/16/21",
        "name":"Carnaval"
      },
      {
        "date":"04/02/21",
        "name":"Páscoa"
      },
      {
        "date":"04/21/21",
        "name":"Tiradentes"
      },
      {
        "date":"05/01/21",
        "name":"Dia do Trabalho"
      },
      {
        "date":"06/03/21",
        "name":"Corpus Christi"
      },
      {
        "date":"09/07/21",
        "name":"Independencia"
      },
      {
        "date":"10/12/21",
        "name":"Nossa Sr.a Aparecida"
      },
      {
        "date":"11/02/21",
        "name":"Finados"
      },
      {
        "date":"11/15/21",
        "name":"Republica"
      },
      {
        "date":"12/25/21",
        "name":"Natal"
      },
      {
        "date":"01/01/22",
        "name":"Confrat Univ"
      },
      {
        "date":"02/28/22",
        "name":"Carnaval"
      },
      {
        "date":"03/01/22",
        "name":"Carnaval"
      },
      {
        "date":"04/15/22",
        "name":"Páscoa"
      },
      {
        "date":"04/21/22",
        "name":"Tiradentes"
      },
      {
        "date":"05/01/22",
        "name":"Dia do Trabalho"
      },
      {
        "date":"06/16/22",
        "name":"Corpus Christi"
      },
      {
        "date":"09/07/22",
        "name":"Independencia"
      },
      {
        "date":"10/12/22",
        "name":"Nossa Sr.a Aparecida"
      },
      {
        "date":"11/02/22",
        "name":"Finados"
      },
      {
        "date":"11/15/22",
        "name":"Republica"
      },
      {
        "date":"12/25/22",
        "name":"Natal"
      },
      {
        "date":"01/01/23",
        "name":"Confrat Univ"
      },
      {
        "date":"02/20/23",
        "name":"Carnaval"
      },
      {
        "date":"02/21/23",
        "name":"Carnaval"
      },
      {
        "date":"04/07/23",
        "name":"Páscoa"
      },
      {
        "date":"04/21/23",
        "name":"Tiradentes"
      },
      {
        "date":"05/01/23",
        "name":"Dia do Trabalho"
      },
      {
        "date":"06/08/23",
        "name":"Corpus Christi"
      },
      {
        "date":"09/07/23",
        "name":"Independencia"
      },
      {
        "date":"10/12/23",
        "name":"Nossa Sr.a Aparecida"
      },
      {
        "date":"11/02/23",
        "name":"Finados"
      },
      {
        "date":"11/15/23",
        "name":"Republica"
      },
      {
        "date":"12/25/23",
        "name":"Natal"
      },
      {
        "date":"01/01/24",
        "name":"Confrat Univ"
      },
      {
        "date":"02/12/24",
        "name":"Carnaval"
      },
      {
        "date":"02/13/24",
        "name":"Carnaval"
      },
      {
        "date":"03/29/24",
        "name":"Páscoa"
      },
      {
        "date":"04/21/24",
        "name":"Tiradentes"
      },
      {
        "date":"05/01/24",
        "name":"Dia do Trabalho"
      },
      {
        "date":"05/30/24",
        "name":"Corpus Christi"
      },
      {
        "date":"09/07/24",
        "name":"Independencia"
      },
      {
        "date":"10/12/24",
        "name":"Nossa Sr.a Aparecida"
      },
      {
        "date":"11/02/24",
        "name":"Finados"
      },
      {
        "date":"11/15/24",
        "name":"Republica"
      },
      {
        "date":"12/25/24",
        "name":"Natal"
      },
      {
        "date":"01/01/25",
        "name":"Confrat Univ"
      },
      {
        "date":"03/03/25",
        "name":"Carnaval"
      },
      {
        "date":"03/04/25",
        "name":"Carnaval"
      },
      {
        "date":"04/18/25",
        "name":"Páscoa"
      },
      {
        "date":"04/21/25",
        "name":"Tiradentes"
      },
      {
        "date":"05/01/25",
        "name":"Dia do Trabalho"
      },
      {
        "date":"06/19/25",
        "name":"Corpus Christi"
      },
      {
        "date":"09/07/25",
        "name":"Independencia"
      },
      {
        "date":"10/12/25",
        "name":"Nossa Sr.a Aparecida"
      },
      {
        "date":"11/02/25",
        "name":"Finados"
      },
      {
        "date":"11/15/25",
        "name":"Republica"
      },
      {
        "date":"12/25/25",
        "name":"Natal"
      },
      {
        "date":"01/01/26",
        "name":"Confrat Univ"
      },
      {
        "date":"02/16/26",
        "name":"Carnaval"
      },
      {
        "date":"02/17/26",
        "name":"Carnaval"
      },
      {
        "date":"04/03/26",
        "name":"Páscoa"
      },
      {
        "date":"04/21/26",
        "name":"Tiradentes"
      },
      {
        "date":"05/01/26",
        "name":"Dia do Trabalho"
      },
      {
        "date":"06/04/26",
        "name":"Corpus Christi"
      },
      {
        "date":"09/07/26",
        "name":"Independencia"
      },
      {
        "date":"10/12/26",
        "name":"Nossa Sr.a Aparecida"
      },
      {
        "date":"11/02/26",
        "name":"Finados"
      },
      {
        "date":"11/15/26",
        "name":"Republica"
      },
      {
        "date":"12/25/26",
        "name":"Natal"
      },
      {
        "date":"01/01/27",
        "name":"Confrat Univ"
      },
      {
        "date":"02/08/27",
        "name":"Carnaval"
      },
      {
        "date":"02/09/27",
        "name":"Carnaval"
      },
      {
        "date":"03/26/27",
        "name":"Páscoa"
      },
      {
        "date":"04/21/27",
        "name":"Tiradentes"
      },
      {
        "date":"05/01/27",
        "name":"Dia do Trabalho"
      },
      {
        "date":"05/27/27",
        "name":"Corpus Christi"
      },
      {
        "date":"09/07/27",
        "name":"Independencia"
      },
      {
        "date":"10/12/27",
        "name":"Nossa Sr.a Aparecida"
      },
      {
        "date":"11/02/27",
        "name":"Finados"
      },
      {
        "date":"11/15/27",
        "name":"Republica"
      },
      {
        "date":"12/25/27",
        "name":"Natal"
      },
      {
        "date":"01/01/28",
        "name":"Confrat Univ"
      },
      {
        "date":"02/28/28",
        "name":"Carnaval"
      },
      {
        "date":"02/29/28",
        "name":"Carnaval"
      },
      {
        "date":"04/14/28",
        "name":"Páscoa"
      },
      {
        "date":"04/21/28",
        "name":"Tiradentes"
      },
      {
        "date":"05/01/28",
        "name":"Dia do Trabalho"
      },
      {
        "date":"06/15/28",
        "name":"Corpus Christi"
      },
      {
        "date":"09/07/28",
        "name":"Independencia"
      },
      {
        "date":"10/12/28",
        "name":"Nossa Sr.a Aparecida"
      },
      {
        "date":"11/02/28",
        "name":"Finados"
      },
      {
        "date":"11/15/28",
        "name":"Republica"
      },
      {
        "date":"12/25/28",
        "name":"Natal"
      },
      {
        "date":"01/01/29",
        "name":"Confrat Univ"
      },
      {
        "date":"02/12/29",
        "name":"Carnaval"
      },
      {
        "date":"02/13/29",
        "name":"Carnaval"
      },
      {
        "date":"03/30/29",
        "name":"Páscoa"
      },
      {
        "date":"04/21/29",
        "name":"Tiradentes"
      },
      {
        "date":"05/01/29",
        "name":"Dia do Trabalho"
      },
      {
        "date":"05/31/29",
        "name":"Corpus Christi"
      },
      {
        "date":"09/07/29",
        "name":"Independencia"
      },
      {
        "date":"10/12/29",
        "name":"Nossa Sr.a Aparecida"
      },
      {
        "date":"11/02/29",
        "name":"Finados"
      },
      {
        "date":"11/15/29",
        "name":"Republica"
      },
      {
        "date":"12/25/29",
        "name":"Natal"
      },
      {
        "date":"01/01/30",
        "name":"Confrat Univ"
      },
      {
        "date":"03/04/30",
        "name":"Carnaval"
      },
      {
        "date":"03/05/30",
        "name":"Carnaval"
      },
      {
        "date":"04/19/30",
        "name":"Páscoa"
      },
      {
        "date":"04/21/30",
        "name":"Tiradentes"
      },
      {
        "date":"05/01/30",
        "name":"Dia do Trabalho"
      },
      {
        "date":"06/20/30",
        "name":"Corpus Christi"
      },
      {
        "date":"09/07/30",
        "name":"Independencia"
      },
      {
        "date":"10/12/30",
        "name":"Nossa Sr.a Aparecida"
      },
      {
        "date":"11/02/30",
        "name":"Finados"
      },
      {
        "date":"11/15/30",
        "name":"Republica"
      },
      {
        "date":"12/25/30",
        "name":"Natal"
      },
      {
        "date":"01/01/31",
        "name":"Confrat Univ"
      },
      {
        "date":"02/24/31",
        "name":"Carnaval"
      },
      {
        "date":"02/25/31",
        "name":"Carnaval"
      },
      {
        "date":"04/11/31",
        "name":"Páscoa"
      },
      {
        "date":"04/21/31",
        "name":"Tiradentes"
      },
      {
        "date":"05/01/31",
        "name":"Dia do Trabalho"
      },
      {
        "date":"06/12/31",
        "name":"Corpus Christi"
      },
      {
        "date":"09/07/31",
        "name":"Independencia"
      },
      {
        "date":"10/12/31",
        "name":"Nossa Sr.a Aparecida"
      },
      {
        "date":"11/02/31",
        "name":"Finados"
      },
      {
        "date":"11/15/31",
        "name":"Republica"
      },
      {
        "date":"12/25/31",
        "name":"Natal"
      },
      {
        "date":"01/01/32",
        "name":"Confrat Univ"
      },
      {
        "date":"02/09/32",
        "name":"Carnaval"
      },
      {
        "date":"02/10/32",
        "name":"Carnaval"
      },
      {
        "date":"03/26/32",
        "name":"Páscoa"
      },
      {
        "date":"04/21/32",
        "name":"Tiradentes"
      },
      {
        "date":"05/01/32",
        "name":"Dia do Trabalho"
      },
      {
        "date":"05/27/32",
        "name":"Corpus Christi"
      },
      {
        "date":"09/07/32",
        "name":"Independencia"
      },
      {
        "date":"10/12/32",
        "name":"Nossa Sr.a Aparecida"
      },
      {
        "date":"11/02/32",
        "name":"Finados"
      },
      {
        "date":"11/15/32",
        "name":"Republica"
      },
      {
        "date":"12/25/32",
        "name":"Natal"
      },
      {
        "date":"01/01/33",
        "name":"Confrat Univ"
      },
      {
        "date":"02/28/33",
        "name":"Carnaval"
      },
      {
        "date":"03/01/33",
        "name":"Carnaval"
      },
      {
        "date":"04/15/33",
        "name":"Páscoa"
      },
      {
        "date":"04/21/33",
        "name":"Tiradentes"
      },
      {
        "date":"05/01/33",
        "name":"Dia do Trabalho"
      },
      {
        "date":"06/16/33",
        "name":"Corpus Christi"
      },
      {
        "date":"09/07/33",
        "name":"Independencia"
      },
      {
        "date":"10/12/33",
        "name":"Nossa Sr.a Aparecida"
      },
      {
        "date":"11/02/33",
        "name":"Finados"
      },
      {
        "date":"11/15/33",
        "name":"Republica"
      },
      {
        "date":"12/25/33",
        "name":"Natal"
      },
      {
        "date":"01/01/34",
        "name":"Confrat Univ"
      },
      {
        "date":"02/20/34",
        "name":"Carnaval"
      },
      {
        "date":"02/21/34",
        "name":"Carnaval"
      },
      {
        "date":"04/07/34",
        "name":"Páscoa"
      },
      {
        "date":"04/21/34",
        "name":"Tiradentes"
      },
      {
        "date":"05/01/34",
        "name":"Dia do Trabalho"
      },
      {
        "date":"06/08/34",
        "name":"Corpus Christi"
      },
      {
        "date":"09/07/34",
        "name":"Independencia"
      },
      {
        "date":"10/12/34",
        "name":"Nossa Sr.a Aparecida"
      },
      {
        "date":"11/02/34",
        "name":"Finados"
      },
      {
        "date":"11/15/34",
        "name":"Republica"
      },
      {
        "date":"12/25/34",
        "name":"Natal"
      },
      {
        "date":"01/01/35",
        "name":"Confrat Univ"
      },
      {
        "date":"02/05/35",
        "name":"Carnaval"
      },
      {
        "date":"02/06/35",
        "name":"Carnaval"
      },
      {
        "date":"03/23/35",
        "name":"Páscoa"
      },
      {
        "date":"04/21/35",
        "name":"Tiradentes"
      },
      {
        "date":"05/01/35",
        "name":"Dia do Trabalho"
      },
      {
        "date":"05/24/35",
        "name":"Corpus Christi"
      },
      {
        "date":"09/07/35",
        "name":"Independencia"
      },
      {
        "date":"10/12/35",
        "name":"Nossa Sr.a Aparecida"
      },
      {
        "date":"11/02/35",
        "name":"Finados"
      },
      {
        "date":"11/15/35",
        "name":"Republica"
      },
      {
        "date":"12/25/35",
        "name":"Natal"
      },
      {
        "date":"01/01/36",
        "name":"Confrat Univ"
      },
      {
        "date":"02/25/36",
        "name":"Carnaval"
      },
      {
        "date":"02/26/36",
        "name":"Carnaval"
      },
      {
        "date":"04/11/36",
        "name":"Páscoa"
      },
      {
        "date":"04/21/36",
        "name":"Tiradentes"
      },
      {
        "date":"05/01/36",
        "name":"Dia do Trabalho"
      },
      {
        "date":"06/12/36",
        "name":"Corpus Christi"
      },
      {
        "date":"09/07/36",
        "name":"Independencia"
      },
      {
        "date":"10/12/36",
        "name":"Nossa Sr.a Aparecida"
      },
      {
        "date":"11/02/36",
        "name":"Finados"
      },
      {
        "date":"11/15/36",
        "name":"Republica"
      },
      {
        "date":"12/25/36",
        "name":"Natal"
      },
      {
        "date":"01/01/37",
        "name":"Confrat Univ"
      },
      {
        "date":"02/16/37",
        "name":"Carnaval"
      },
      {
        "date":"02/17/37",
        "name":"Carnaval"
      },
      {
        "date":"04/03/37",
        "name":"Páscoa"
      },
      {
        "date":"04/21/37",
        "name":"Tiradentes"
      },
      {
        "date":"05/01/37",
        "name":"Dia do Trabalho"
      },
      {
        "date":"06/04/37",
        "name":"Corpus Christi"
      },
      {
        "date":"09/07/37",
        "name":"Independencia"
      },
      {
        "date":"10/12/37",
        "name":"Nossa Sr.a Aparecida"
      },
      {
        "date":"11/02/37",
        "name":"Finados"
      },
      {
        "date":"11/15/37",
        "name":"Republica"
      },
      {
        "date":"12/25/37",
        "name":"Natal"
      },
      {
        "date":"01/01/38",
        "name":"Confrat Univ"
      },
      {
        "date":"03/08/38",
        "name":"Carnaval"
      },
      {
        "date":"03/09/38",
        "name":"Carnaval"
      },
      {
        "date":"04/21/38",
        "name":"Tiradentes"
      },
      {
        "date":"04/23/38",
        "name":"Páscoa"
      },
      {
        "date":"05/01/38",
        "name":"Dia do Trabalho"
      },
      {
        "date":"06/24/38",
        "name":"Corpus Christi"
      },
      {
        "date":"09/07/38",
        "name":"Independencia"
      },
      {
        "date":"10/12/38",
        "name":"Nossa Sr.a Aparecida"
      },
      {
        "date":"11/02/38",
        "name":"Finados"
      },
      {
        "date":"11/15/38",
        "name":"Republica"
      },
      {
        "date":"12/25/38",
        "name":"Natal"
      },
      {
        "date":"01/01/39",
        "name":"Confrat Univ"
      },
      {
        "date":"02/21/39",
        "name":"Carnaval"
      },
      {
        "date":"02/22/39",
        "name":"Carnaval"
      },
      {
        "date":"04/08/39",
        "name":"Páscoa"
      },
      {
        "date":"04/21/39",
        "name":"Tiradentes"
      },
      {
        "date":"05/01/39",
        "name":"Dia do Trabalho"
      },
      {
        "date":"06/09/39",
        "name":"Corpus Christi"
      },
      {
        "date":"09/07/39",
        "name":"Independencia"
      },
      {
        "date":"10/12/39",
        "name":"Nossa Sr.a Aparecida"
      },
      {
        "date":"11/02/39",
        "name":"Finados"
      },
      {
        "date":"11/15/39",
        "name":"Republica"
      },
      {
        "date":"12/25/39",
        "name":"Natal"
      },
      {
        "date":"01/01/40",
        "name":"Confrat Univ"
      },
      {
        "date":"02/13/40",
        "name":"Carnaval"
      },
      {
        "date":"02/14/40",
        "name":"Carnaval"
      },
      {
        "date":"03/30/40",
        "name":"Páscoa"
      },
      {
        "date":"04/21/40",
        "name":"Tiradentes"
      },
      {
        "date":"05/01/40",
        "name":"Dia do Trabalho"
      },
      {
        "date":"05/31/40",
        "name":"Corpus Christi"
      },
      {
        "date":"09/07/40",
        "name":"Independencia"
      },
      {
        "date":"10/12/40",
        "name":"Nossa Sr.a Aparecida"
      },
      {
        "date":"11/02/40",
        "name":"Finados"
      },
      {
        "date":"11/15/40",
        "name":"Republica"
      },
      {
        "date":"12/25/40",
        "name":"Natal"
      },
      {
        "date":"01/01/41",
        "name":"Confrat Univ"
      },
      {
        "date":"03/04/41",
        "name":"Carnaval"
      },
      {
        "date":"03/05/41",
        "name":"Carnaval"
      },
      {
        "date":"04/19/41",
        "name":"Páscoa"
      },
      {
        "date":"04/21/41",
        "name":"Tiradentes"
      },
      {
        "date":"05/01/41",
        "name":"Dia do Trabalho"
      },
      {
        "date":"06/20/41",
        "name":"Corpus Christi"
      },
      {
        "date":"09/07/41",
        "name":"Independencia"
      },
      {
        "date":"10/12/41",
        "name":"Nossa Sr.a Aparecida"
      },
      {
        "date":"11/02/41",
        "name":"Finados"
      },
      {
        "date":"11/15/41",
        "name":"Republica"
      },
      {
        "date":"12/25/41",
        "name":"Natal"
      },
      {
        "date":"01/01/42",
        "name":"Confrat Univ"
      },
      {
        "date":"02/17/42",
        "name":"Carnaval"
      },
      {
        "date":"02/18/42",
        "name":"Carnaval"
      },
      {
        "date":"04/04/42",
        "name":"Páscoa"
      },
      {
        "date":"04/21/42",
        "name":"Tiradentes"
      },
      {
        "date":"05/01/42",
        "name":"Dia do Trabalho"
      },
      {
        "date":"06/05/42",
        "name":"Corpus Christi"
      },
      {
        "date":"09/07/42",
        "name":"Independencia"
      },
      {
        "date":"10/12/42",
        "name":"Nossa Sr.a Aparecida"
      },
      {
        "date":"11/02/42",
        "name":"Finados"
      },
      {
        "date":"11/15/42",
        "name":"Republica"
      },
      {
        "date":"12/25/42",
        "name":"Natal"
      },
      {
        "date":"01/01/43",
        "name":"Confrat Univ"
      },
      {
        "date":"02/09/43",
        "name":"Carnaval"
      },
      {
        "date":"02/10/43",
        "name":"Carnaval"
      },
      {
        "date":"03/27/43",
        "name":"Páscoa"
      },
      {
        "date":"04/21/43",
        "name":"Tiradentes"
      },
      {
        "date":"05/01/43",
        "name":"Dia do Trabalho"
      },
      {
        "date":"05/28/43",
        "name":"Corpus Christi"
      },
      {
        "date":"09/07/43",
        "name":"Independencia"
      },
      {
        "date":"10/12/43",
        "name":"Nossa Sr.a Aparecida"
      },
      {
        "date":"11/02/43",
        "name":"Finados"
      },
      {
        "date":"11/15/43",
        "name":"Republica"
      },
      {
        "date":"12/25/43",
        "name":"Natal"
      },
      {
        "date":"01/01/44",
        "name":"Confrat Univ"
      },
      {
        "date":"02/29/44",
        "name":"Carnaval"
      },
      {
        "date":"03/01/44",
        "name":"Carnaval"
      },
      {
        "date":"04/15/44",
        "name":"Páscoa"
      },
      {
        "date":"04/21/44",
        "name":"Tiradentes"
      },
      {
        "date":"05/01/44",
        "name":"Dia do Trabalho"
      },
      {
        "date":"06/16/44",
        "name":"Corpus Christi"
      },
      {
        "date":"09/07/44",
        "name":"Independencia"
      },
      {
        "date":"10/12/44",
        "name":"Nossa Sr.a Aparecida"
      },
      {
        "date":"11/02/44",
        "name":"Finados"
      },
      {
        "date":"11/15/44",
        "name":"Republica"
      },
      {
        "date":"12/25/44",
        "name":"Natal"
      },
      {
        "date":"01/01/45",
        "name":"Confrat Univ"
      },
      {
        "date":"02/20/45",
        "name":"Carnaval"
      },
      {
        "date":"02/21/45",
        "name":"Carnaval"
      },
      {
        "date":"04/07/45",
        "name":"Páscoa"
      },
      {
        "date":"04/21/45",
        "name":"Tiradentes"
      },
      {
        "date":"05/01/45",
        "name":"Dia do Trabalho"
      },
      {
        "date":"06/08/45",
        "name":"Corpus Christi"
      },
      {
        "date":"09/07/45",
        "name":"Independencia"
      },
      {
        "date":"10/12/45",
        "name":"Nossa Sr.a Aparecida"
      },
      {
        "date":"11/02/45",
        "name":"Finados"
      },
      {
        "date":"11/15/45",
        "name":"Republica"
      },
      {
        "date":"12/25/45",
        "name":"Natal"
      },
      {
        "date":"01/01/46",
        "name":"Confrat Univ"
      },
      {
        "date":"02/05/46",
        "name":"Carnaval"
      },
      {
        "date":"02/06/46",
        "name":"Carnaval"
      },
      {
        "date":"03/23/46",
        "name":"Páscoa"
      },
      {
        "date":"04/21/46",
        "name":"Tiradentes"
      },
      {
        "date":"05/01/46",
        "name":"Dia do Trabalho"
      },
      {
        "date":"05/24/46",
        "name":"Corpus Christi"
      },
      {
        "date":"09/07/46",
        "name":"Independencia"
      },
      {
        "date":"10/12/46",
        "name":"Nossa Sr.a Aparecida"
      },
      {
        "date":"11/02/46",
        "name":"Finados"
      },
      {
        "date":"11/15/46",
        "name":"Republica"
      },
      {
        "date":"12/25/46",
        "name":"Natal"
      },
      {
        "date":"01/01/47",
        "name":"Confrat Univ"
      },
      {
        "date":"02/25/47",
        "name":"Carnaval"
      },
      {
        "date":"02/26/47",
        "name":"Carnaval"
      },
      {
        "date":"04/12/47",
        "name":"Páscoa"
      },
      {
        "date":"04/21/47",
        "name":"Tiradentes"
      },
      {
        "date":"05/01/47",
        "name":"Dia do Trabalho"
      },
      {
        "date":"06/13/47",
        "name":"Corpus Christi"
      },
      {
        "date":"09/07/47",
        "name":"Independencia"
      },
      {
        "date":"10/12/47",
        "name":"Nossa Sr.a Aparecida"
      },
      {
        "date":"11/02/47",
        "name":"Finados"
      },
      {
        "date":"11/15/47",
        "name":"Republica"
      },
      {
        "date":"12/25/47",
        "name":"Natal"
      },
      {
        "date":"01/01/48",
        "name":"Confrat Univ"
      },
      {
        "date":"02/17/48",
        "name":"Carnaval"
      },
      {
        "date":"02/18/48",
        "name":"Carnaval"
      },
      {
        "date":"04/03/48",
        "name":"Páscoa"
      },
      {
        "date":"04/21/48",
        "name":"Tiradentes"
      },
      {
        "date":"05/01/48",
        "name":"Dia do Trabalho"
      },
      {
        "date":"06/04/48",
        "name":"Corpus Christi"
      },
      {
        "date":"09/07/48",
        "name":"Independencia"
      },
      {
        "date":"10/12/48",
        "name":"Nossa Sr.a Aparecida"
      },
      {
        "date":"11/02/48",
        "name":"Finados"
      },
      {
        "date":"11/15/48",
        "name":"Republica"
      },
      {
        "date":"12/25/48",
        "name":"Natal"
      },
      {
        "date":"01/01/49",
        "name":"Confrat Univ"
      },
      {
        "date":"03/01/49",
        "name":"Carnaval"
      },
      {
        "date":"03/02/49",
        "name":"Carnaval"
      },
      {
        "date":"04/16/49",
        "name":"Páscoa"
      },
      {
        "date":"04/21/49",
        "name":"Tiradentes"
      },
      {
        "date":"05/01/49",
        "name":"Dia do Trabalho"
      },
      {
        "date":"06/17/49",
        "name":"Corpus Christi"
      },
      {
        "date":"09/07/49",
        "name":"Independencia"
      },
      {
        "date":"10/12/49",
        "name":"Nossa Sr.a Aparecida"
      },
      {
        "date":"11/02/49",
        "name":"Finados"
      },
      {
        "date":"11/15/49",
        "name":"Republica"
      },
      {
        "date":"12/25/49",
        "name":"Natal"
      },
      {
        "date":"01/01/50",
        "name":"Confrat Univ"
      },
      {
        "date":"02/21/50",
        "name":"Carnaval"
      },
      {
        "date":"02/22/50",
        "name":"Carnaval"
      },
      {
        "date":"04/08/50",
        "name":"Páscoa"
      },
      {
        "date":"04/21/50",
        "name":"Tiradentes"
      },
      {
        "date":"05/01/50",
        "name":"Dia do Trabalho"
      },
      {
        "date":"06/09/50",
        "name":"Corpus Christi"
      },
      {
        "date":"09/07/50",
        "name":"Independencia"
      },
      {
        "date":"10/12/50",
        "name":"Nossa Sr.a Aparecida"
      },
      {
        "date":"11/02/50",
        "name":"Finados"
      },
      {
        "date":"11/15/50",
        "name":"Republica"
      },
      {
        "date":"12/25/50",
        "name":"Natal"
      },
      {
        "date":"01/01/51",
        "name":"Confrat Univ"
      },
      {
        "date":"02/13/51",
        "name":"Carnaval"
      },
      {
        "date":"02/14/51",
        "name":"Carnaval"
      },
      {
        "date":"03/31/51",
        "name":"Páscoa"
      },
      {
        "date":"04/21/51",
        "name":"Tiradentes"
      },
      {
        "date":"05/01/51",
        "name":"Dia do Trabalho"
      },
      {
        "date":"06/01/51",
        "name":"Corpus Christi"
      },
      {
        "date":"09/07/51",
        "name":"Independencia"
      },
      {
        "date":"10/12/51",
        "name":"Nossa Sr.a Aparecida"
      },
      {
        "date":"11/02/51",
        "name":"Finados"
      },
      {
        "date":"11/15/51",
        "name":"Republica"
      },
      {
        "date":"12/25/51",
        "name":"Natal"
      },
      {
        "date":"01/01/52",
        "name":"Confrat Univ"
      },
      {
        "date":"03/04/52",
        "name":"Carnaval"
      },
      {
        "date":"03/05/52",
        "name":"Carnaval"
      },
      {
        "date":"04/19/52",
        "name":"Páscoa"
      },
      {
        "date":"04/21/52",
        "name":"Tiradentes"
      },
      {
        "date":"05/01/52",
        "name":"Dia do Trabalho"
      },
      {
        "date":"06/20/52",
        "name":"Corpus Christi"
      },
      {
        "date":"09/07/52",
        "name":"Independencia"
      },
      {
        "date":"10/12/52",
        "name":"Nossa Sr.a Aparecida"
      },
      {
        "date":"11/02/52",
        "name":"Finados"
      },
      {
        "date":"11/15/52",
        "name":"Republica"
      },
      {
        "date":"12/25/52",
        "name":"Natal"
      },
      {
        "date":"01/01/53",
        "name":"Confrat Univ"
      },
      {
        "date":"02/17/53",
        "name":"Carnaval"
      },
      {
        "date":"02/18/53",
        "name":"Carnaval"
      },
      {
        "date":"04/04/53",
        "name":"Páscoa"
      },
      {
        "date":"04/21/53",
        "name":"Tiradentes"
      },
      {
        "date":"05/01/53",
        "name":"Dia do Trabalho"
      },
      {
        "date":"06/05/53",
        "name":"Corpus Christi"
      },
      {
        "date":"09/07/53",
        "name":"Independencia"
      },
      {
        "date":"10/12/53",
        "name":"Nossa Sr.a Aparecida"
      },
      {
        "date":"11/02/53",
        "name":"Finados"
      },
      {
        "date":"11/15/53",
        "name":"Republica"
      },
      {
        "date":"12/25/53",
        "name":"Natal"
      },
      {
        "date":"01/01/54",
        "name":"Confrat Univ"
      },
      {
        "date":"02/09/54",
        "name":"Carnaval"
      },
      {
        "date":"02/10/54",
        "name":"Carnaval"
      },
      {
        "date":"03/27/54",
        "name":"Páscoa"
      },
      {
        "date":"04/21/54",
        "name":"Tiradentes"
      },
      {
        "date":"05/01/54",
        "name":"Dia do Trabalho"
      },
      {
        "date":"05/28/54",
        "name":"Corpus Christi"
      },
      {
        "date":"09/07/54",
        "name":"Independencia"
      },
      {
        "date":"10/12/54",
        "name":"Nossa Sr.a Aparecida"
      },
      {
        "date":"11/02/54",
        "name":"Finados"
      },
      {
        "date":"11/15/54",
        "name":"Republica"
      },
      {
        "date":"12/25/54",
        "name":"Natal"
      },
      {
        "date":"01/01/55",
        "name":"Confrat Univ"
      },
      {
        "date":"03/01/55",
        "name":"Carnaval"
      },
      {
        "date":"03/02/55",
        "name":"Carnaval"
      },
      {
        "date":"04/16/55",
        "name":"Páscoa"
      },
      {
        "date":"04/21/55",
        "name":"Tiradentes"
      },
      {
        "date":"05/01/55",
        "name":"Dia do Trabalho"
      },
      {
        "date":"06/17/55",
        "name":"Corpus Christi"
      },
      {
        "date":"09/07/55",
        "name":"Independencia"
      },
      {
        "date":"10/12/55",
        "name":"Nossa Sr.a Aparecida"
      },
      {
        "date":"11/02/55",
        "name":"Finados"
      },
      {
        "date":"11/15/55",
        "name":"Republica"
      },
      {
        "date":"12/25/55",
        "name":"Natal"
      },
      {
        "date":"01/01/56",
        "name":"Confrat Univ"
      },
      {
        "date":"02/14/56",
        "name":"Carnaval"
      },
      {
        "date":"02/15/56",
        "name":"Carnaval"
      },
      {
        "date":"03/31/56",
        "name":"Páscoa"
      },
      {
        "date":"04/21/56",
        "name":"Tiradentes"
      },
      {
        "date":"05/01/56",
        "name":"Dia do Trabalho"
      },
      {
        "date":"06/01/56",
        "name":"Corpus Christi"
      },
      {
        "date":"09/07/56",
        "name":"Independencia"
      },
      {
        "date":"10/12/56",
        "name":"Nossa Sr.a Aparecida"
      },
      {
        "date":"11/02/56",
        "name":"Finados"
      },
      {
        "date":"11/15/56",
        "name":"Republica"
      },
      {
        "date":"12/25/56",
        "name":"Natal"
      },
      {
        "date":"01/01/57",
        "name":"Confrat Univ"
      },
      {
        "date":"03/05/57",
        "name":"Carnaval"
      },
      {
        "date":"03/06/57",
        "name":"Carnaval"
      },
      {
        "date":"04/20/57",
        "name":"Páscoa"
      },
      {
        "date":"04/21/57",
        "name":"Tiradentes"
      },
      {
        "date":"05/01/57",
        "name":"Dia do Trabalho"
      },
      {
        "date":"06/21/57",
        "name":"Corpus Christi"
      },
      {
        "date":"09/07/57",
        "name":"Independencia"
      },
      {
        "date":"10/12/57",
        "name":"Nossa Sr.a Aparecida"
      },
      {
        "date":"11/02/57",
        "name":"Finados"
      },
      {
        "date":"11/15/57",
        "name":"Republica"
      },
      {
        "date":"12/25/57",
        "name":"Natal"
      },
      {
        "date":"01/01/58",
        "name":"Confrat Univ"
      },
      {
        "date":"02/25/58",
        "name":"Carnaval"
      },
      {
        "date":"02/26/58",
        "name":"Carnaval"
      },
      {
        "date":"04/12/58",
        "name":"Páscoa"
      },
      {
        "date":"04/21/58",
        "name":"Tiradentes"
      },
      {
        "date":"05/01/58",
        "name":"Dia do Trabalho"
      },
      {
        "date":"06/13/58",
        "name":"Corpus Christi"
      },
      {
        "date":"09/07/58",
        "name":"Independencia"
      },
      {
        "date":"10/12/58",
        "name":"Nossa Sr.a Aparecida"
      },
      {
        "date":"11/02/58",
        "name":"Finados"
      },
      {
        "date":"11/15/58",
        "name":"Republica"
      },
      {
        "date":"12/25/58",
        "name":"Natal"
      },
      {
        "date":"01/01/59",
        "name":"Confrat Univ"
      },
      {
        "date":"02/10/59",
        "name":"Carnaval"
      },
      {
        "date":"02/11/59",
        "name":"Carnaval"
      },
      {
        "date":"03/28/59",
        "name":"Páscoa"
      },
      {
        "date":"04/21/59",
        "name":"Tiradentes"
      },
      {
        "date":"05/01/59",
        "name":"Dia do Trabalho"
      },
      {
        "date":"05/29/59",
        "name":"Corpus Christi"
      },
      {
        "date":"09/07/59",
        "name":"Independencia"
      },
      {
        "date":"10/12/59",
        "name":"Nossa Sr.a Aparecida"
      },
      {
        "date":"11/02/59",
        "name":"Finados"
      },
      {
        "date":"11/15/59",
        "name":"Republica"
      },
      {
        "date":"12/25/59",
        "name":"Natal"
      },
      {
        "date":"01/01/60",
        "name":"Confrat Univ"
      },
      {
        "date":"03/01/60",
        "name":"Carnaval"
      },
      {
        "date":"03/02/60",
        "name":"Carnaval"
      },
      {
        "date":"04/16/60",
        "name":"Páscoa"
      },
      {
        "date":"04/21/60",
        "name":"Tiradentes"
      },
      {
        "date":"05/01/60",
        "name":"Dia do Trabalho"
      },
      {
        "date":"06/17/60",
        "name":"Corpus Christi"
      },
      {
        "date":"09/07/60",
        "name":"Independencia"
      },
      {
        "date":"10/12/60",
        "name":"Nossa Sr.a Aparecida"
      },
      {
        "date":"11/02/60",
        "name":"Finados"
      },
      {
        "date":"11/15/60",
        "name":"Republica"
      },
      {
        "date":"12/25/60",
        "name":"Natal"
      },
      {
        "date":"01/01/61",
        "name":"Confrat Univ"
      },
      {
        "date":"02/21/61",
        "name":"Carnaval"
      },
      {
        "date":"02/22/61",
        "name":"Carnaval"
      },
      {
        "date":"04/08/61",
        "name":"Páscoa"
      },
      {
        "date":"04/21/61",
        "name":"Tiradentes"
      },
      {
        "date":"05/01/61",
        "name":"Dia do Trabalho"
      },
      {
        "date":"06/09/61",
        "name":"Corpus Christi"
      },
      {
        "date":"09/07/61",
        "name":"Independencia"
      },
      {
        "date":"10/12/61",
        "name":"Nossa Sr.a Aparecida"
      },
      {
        "date":"11/02/61",
        "name":"Finados"
      },
      {
        "date":"11/15/61",
        "name":"Republica"
      },
      {
        "date":"12/25/61",
        "name":"Natal"
      },
      {
        "date":"01/01/62",
        "name":"Confrat Univ"
      },
      {
        "date":"02/06/62",
        "name":"Carnaval"
      },
      {
        "date":"02/07/62",
        "name":"Carnaval"
      },
      {
        "date":"03/24/62",
        "name":"Páscoa"
      },
      {
        "date":"04/21/62",
        "name":"Tiradentes"
      },
      {
        "date":"05/01/62",
        "name":"Dia do Trabalho"
      },
      {
        "date":"05/25/62",
        "name":"Corpus Christi"
      },
      {
        "date":"09/07/62",
        "name":"Independencia"
      },
      {
        "date":"10/12/62",
        "name":"Nossa Sr.a Aparecida"
      },
      {
        "date":"11/02/62",
        "name":"Finados"
      },
      {
        "date":"11/15/62",
        "name":"Republica"
      },
      {
        "date":"12/25/62",
        "name":"Natal"
      },
      {
        "date":"01/01/63",
        "name":"Confrat Univ"
      },
      {
        "date":"02/26/63",
        "name":"Carnaval"
      },
      {
        "date":"02/27/63",
        "name":"Carnaval"
      },
      {
        "date":"04/13/63",
        "name":"Páscoa"
      },
      {
        "date":"04/21/63",
        "name":"Tiradentes"
      },
      {
        "date":"05/01/63",
        "name":"Dia do Trabalho"
      },
      {
        "date":"06/14/63",
        "name":"Corpus Christi"
      },
      {
        "date":"09/07/63",
        "name":"Independencia"
      },
      {
        "date":"10/12/63",
        "name":"Nossa Sr.a Aparecida"
      },
      {
        "date":"11/02/63",
        "name":"Finados"
      },
      {
        "date":"11/15/63",
        "name":"Republica"
      },
      {
        "date":"12/25/63",
        "name":"Natal"
      },
      {
        "date":"01/01/64",
        "name":"Confrat Univ"
      },
      {
        "date":"02/18/64",
        "name":"Carnaval"
      },
      {
        "date":"02/19/64",
        "name":"Carnaval"
      },
      {
        "date":"04/04/64",
        "name":"Páscoa"
      },
      {
        "date":"04/21/64",
        "name":"Tiradentes"
      },
      {
        "date":"05/01/64",
        "name":"Dia do Trabalho"
      },
      {
        "date":"06/05/64",
        "name":"Corpus Christi"
      },
      {
        "date":"09/07/64",
        "name":"Independencia"
      },
      {
        "date":"10/12/64",
        "name":"Nossa Sr.a Aparecida"
      },
      {
        "date":"11/02/64",
        "name":"Finados"
      },
      {
        "date":"11/15/64",
        "name":"Republica"
      },
      {
        "date":"12/25/64",
        "name":"Natal"
      },
      {
        "date":"01/01/65",
        "name":"Confrat Univ"
      },
      {
        "date":"02/09/65",
        "name":"Carnaval"
      },
      {
        "date":"02/10/65",
        "name":"Carnaval"
      },
      {
        "date":"03/27/65",
        "name":"Páscoa"
      },
      {
        "date":"04/21/65",
        "name":"Tiradentes"
      },
      {
        "date":"05/01/65",
        "name":"Dia do Trabalho"
      },
      {
        "date":"05/28/65",
        "name":"Corpus Christi"
      },
      {
        "date":"09/07/65",
        "name":"Independencia"
      },
      {
        "date":"10/12/65",
        "name":"Nossa Sr.a Aparecida"
      },
      {
        "date":"11/02/65",
        "name":"Finados"
      },
      {
        "date":"11/15/65",
        "name":"Republica"
      },
      {
        "date":"12/25/65",
        "name":"Natal"
      },
      {
        "date":"01/01/66",
        "name":"Confrat Univ"
      },
      {
        "date":"02/22/66",
        "name":"Carnaval"
      },
      {
        "date":"02/23/66",
        "name":"Carnaval"
      },
      {
        "date":"04/09/66",
        "name":"Páscoa"
      },
      {
        "date":"04/21/66",
        "name":"Tiradentes"
      },
      {
        "date":"05/01/66",
        "name":"Dia do Trabalho"
      },
      {
        "date":"06/10/66",
        "name":"Corpus Christi"
      },
      {
        "date":"09/07/66",
        "name":"Independencia"
      },
      {
        "date":"10/12/66",
        "name":"Nossa Sr.a Aparecida"
      },
      {
        "date":"11/02/66",
        "name":"Finados"
      },
      {
        "date":"11/15/66",
        "name":"Republica"
      },
      {
        "date":"12/25/66",
        "name":"Natal"
      },
      {
        "date":"01/01/67",
        "name":"Confrat Univ"
      },
      {
        "date":"02/14/67",
        "name":"Carnaval"
      },
      {
        "date":"02/15/67",
        "name":"Carnaval"
      },
      {
        "date":"04/01/67",
        "name":"Páscoa"
      },
      {
        "date":"04/21/67",
        "name":"Tiradentes"
      },
      {
        "date":"05/01/67",
        "name":"Dia do Trabalho"
      },
      {
        "date":"06/02/67",
        "name":"Corpus Christi"
      },
      {
        "date":"09/07/67",
        "name":"Independencia"
      },
      {
        "date":"10/12/67",
        "name":"Nossa Sr.a Aparecida"
      },
      {
        "date":"11/02/67",
        "name":"Finados"
      },
      {
        "date":"11/15/67",
        "name":"Republica"
      },
      {
        "date":"12/25/67",
        "name":"Natal"
      },
      {
        "date":"01/01/68",
        "name":"Confrat Univ"
      },
      {
        "date":"03/05/68",
        "name":"Carnaval"
      },
      {
        "date":"03/06/68",
        "name":"Carnaval"
      },
      {
        "date":"04/20/68",
        "name":"Páscoa"
      },
      {
        "date":"04/21/68",
        "name":"Tiradentes"
      },
      {
        "date":"05/01/68",
        "name":"Dia do Trabalho"
      },
      {
        "date":"06/21/68",
        "name":"Corpus Christi"
      },
      {
        "date":"09/07/68",
        "name":"Independencia"
      },
      {
        "date":"10/12/68",
        "name":"Nossa Sr.a Aparecida"
      },
      {
        "date":"11/02/68",
        "name":"Finados"
      },
      {
        "date":"11/15/68",
        "name":"Republica"
      },
      {
        "date":"12/25/68",
        "name":"Natal"
      },
      {
        "date":"01/01/69",
        "name":"Confrat Univ"
      },
      {
        "date":"02/25/69",
        "name":"Carnaval"
      },
      {
        "date":"02/26/69",
        "name":"Carnaval"
      },
      {
        "date":"04/12/69",
        "name":"Páscoa"
      },
      {
        "date":"04/21/69",
        "name":"Tiradentes"
      },
      {
        "date":"05/01/69",
        "name":"Dia do Trabalho"
      },
      {
        "date":"06/13/69",
        "name":"Corpus Christi"
      },
      {
        "date":"09/07/69",
        "name":"Independencia"
      },
      {
        "date":"10/12/69",
        "name":"Nossa Sr.a Aparecida"
      },
      {
        "date":"11/02/69",
        "name":"Finados"
      },
      {
        "date":"11/15/69",
        "name":"Republica"
      },
      {
        "date":"12/25/69",
        "name":"Natal"
      },
      {
        "date":"01/01/70",
        "name":"Confrat Univ"
      },
      {
        "date":"02/10/70",
        "name":"Carnaval"
      },
      {
        "date":"02/11/70",
        "name":"Carnaval"
      },
      {
        "date":"03/28/70",
        "name":"Páscoa"
      },
      {
        "date":"04/21/70",
        "name":"Tiradentes"
      },
      {
        "date":"05/01/70",
        "name":"Dia do Trabalho"
      },
      {
        "date":"05/29/70",
        "name":"Corpus Christi"
      },
      {
        "date":"09/07/70",
        "name":"Independencia"
      },
      {
        "date":"10/12/70",
        "name":"Nossa Sr.a Aparecida"
      },
      {
        "date":"11/02/70",
        "name":"Finados"
      },
      {
        "date":"11/15/70",
        "name":"Republica"
      },
      {
        "date":"12/25/70",
        "name":"Natal"
      },
      {
        "date":"01/01/71",
        "name":"Confrat Univ"
      },
      {
        "date":"03/02/71",
        "name":"Carnaval"
      },
      {
        "date":"03/03/71",
        "name":"Carnaval"
      },
      {
        "date":"04/17/71",
        "name":"Páscoa"
      },
      {
        "date":"04/21/71",
        "name":"Tiradentes"
      },
      {
        "date":"05/01/71",
        "name":"Dia do Trabalho"
      },
      {
        "date":"06/18/71",
        "name":"Corpus Christi"
      },
      {
        "date":"09/07/71",
        "name":"Independencia"
      },
      {
        "date":"10/12/71",
        "name":"Nossa Sr.a Aparecida"
      },
      {
        "date":"11/02/71",
        "name":"Finados"
      },
      {
        "date":"11/15/71",
        "name":"Republica"
      },
      {
        "date":"12/25/71",
        "name":"Natal"
      },
      {
        "date":"01/01/72",
        "name":"Confrat Univ"
      },
      {
        "date":"02/22/72",
        "name":"Carnaval"
      },
      {
        "date":"02/23/72",
        "name":"Carnaval"
      },
      {
        "date":"04/08/72",
        "name":"Páscoa"
      },
      {
        "date":"04/21/72",
        "name":"Tiradentes"
      },
      {
        "date":"05/01/72",
        "name":"Dia do Trabalho"
      },
      {
        "date":"06/09/72",
        "name":"Corpus Christi"
      },
      {
        "date":"09/07/72",
        "name":"Independencia"
      },
      {
        "date":"10/12/72",
        "name":"Nossa Sr.a Aparecida"
      },
      {
        "date":"11/02/72",
        "name":"Finados"
      },
      {
        "date":"11/15/72",
        "name":"Republica"
      },
      {
        "date":"12/25/72",
        "name":"Natal"
      },
      {
        "date":"01/01/73",
        "name":"Confrat Univ"
      },
      {
        "date":"02/06/73",
        "name":"Carnaval"
      },
      {
        "date":"02/07/73",
        "name":"Carnaval"
      },
      {
        "date":"03/24/73",
        "name":"Páscoa"
      },
      {
        "date":"04/21/73",
        "name":"Tiradentes"
      },
      {
        "date":"05/01/73",
        "name":"Dia do Trabalho"
      },
      {
        "date":"05/25/73",
        "name":"Corpus Christi"
      },
      {
        "date":"09/07/73",
        "name":"Independencia"
      },
      {
        "date":"10/12/73",
        "name":"Nossa Sr.a Aparecida"
      },
      {
        "date":"11/02/73",
        "name":"Finados"
      },
      {
        "date":"11/15/73",
        "name":"Republica"
      },
      {
        "date":"12/25/73",
        "name":"Natal"
      },
      {
        "date":"01/01/74",
        "name":"Confrat Univ"
      },
      {
        "date":"02/26/74",
        "name":"Carnaval"
      },
      {
        "date":"02/27/74",
        "name":"Carnaval"
      },
      {
        "date":"04/13/74",
        "name":"Páscoa"
      },
      {
        "date":"04/21/74",
        "name":"Tiradentes"
      },
      {
        "date":"05/01/74",
        "name":"Dia do Trabalho"
      },
      {
        "date":"06/14/74",
        "name":"Corpus Christi"
      },
      {
        "date":"09/07/74",
        "name":"Independencia"
      },
      {
        "date":"10/12/74",
        "name":"Nossa Sr.a Aparecida"
      },
      {
        "date":"11/02/74",
        "name":"Finados"
      },
      {
        "date":"11/15/74",
        "name":"Republica"
      },
      {
        "date":"12/25/74",
        "name":"Natal"
      },
      {
        "date":"01/01/75",
        "name":"Confrat Univ"
      },
      {
        "date":"02/18/75",
        "name":"Carnaval"
      },
      {
        "date":"02/19/75",
        "name":"Carnaval"
      },
      {
        "date":"04/05/75",
        "name":"Páscoa"
      },
      {
        "date":"04/21/75",
        "name":"Tiradentes"
      },
      {
        "date":"05/01/75",
        "name":"Dia do Trabalho"
      },
      {
        "date":"06/06/75",
        "name":"Corpus Christi"
      },
      {
        "date":"09/07/75",
        "name":"Independencia"
      },
      {
        "date":"10/12/75",
        "name":"Nossa Sr.a Aparecida"
      },
      {
        "date":"11/02/75",
        "name":"Finados"
      },
      {
        "date":"11/15/75",
        "name":"Republica"
      },
      {
        "date":"12/25/75",
        "name":"Natal"
      },
      {
        "date":"01/01/76",
        "name":"Confrat Univ"
      },
      {
        "date":"03/02/76",
        "name":"Carnaval"
      },
      {
        "date":"03/03/76",
        "name":"Carnaval"
      },
      {
        "date":"04/17/76",
        "name":"Páscoa"
      },
      {
        "date":"04/21/76",
        "name":"Tiradentes"
      },
      {
        "date":"05/01/76",
        "name":"Dia do Trabalho"
      },
      {
        "date":"06/18/76",
        "name":"Corpus Christi"
      },
      {
        "date":"09/07/76",
        "name":"Independencia"
      },
      {
        "date":"10/12/76",
        "name":"Nossa Sr.a Aparecida"
      },
      {
        "date":"11/02/76",
        "name":"Finados"
      },
      {
        "date":"11/15/76",
        "name":"Republica"
      },
      {
        "date":"12/25/76",
        "name":"Natal"
      },
      {
        "date":"01/01/77",
        "name":"Confrat Univ"
      },
      {
        "date":"02/22/77",
        "name":"Carnaval"
      },
      {
        "date":"02/23/77",
        "name":"Carnaval"
      },
      {
        "date":"04/09/77",
        "name":"Páscoa"
      },
      {
        "date":"04/21/77",
        "name":"Tiradentes"
      },
      {
        "date":"05/01/77",
        "name":"Dia do Trabalho"
      },
      {
        "date":"06/10/77",
        "name":"Corpus Christi"
      },
      {
        "date":"09/07/77",
        "name":"Independencia"
      },
      {
        "date":"10/12/77",
        "name":"Nossa Sr.a Aparecida"
      },
      {
        "date":"11/02/77",
        "name":"Finados"
      },
      {
        "date":"11/15/77",
        "name":"Republica"
      },
      {
        "date":"12/25/77",
        "name":"Natal"
      },
      {
        "date":"01/01/78",
        "name":"Confrat Univ"
      },
      {
        "date":"02/14/78",
        "name":"Carnaval"
      },
      {
        "date":"02/15/78",
        "name":"Carnaval"
      },
      {
        "date":"04/01/78",
        "name":"Páscoa"
      },
      {
        "date":"04/21/78",
        "name":"Tiradentes"
      },
      {
        "date":"05/01/78",
        "name":"Dia do Trabalho"
      },
      {
        "date":"06/02/78",
        "name":"Corpus Christi"
      },
      {
        "date":"09/07/78",
        "name":"Independencia"
      },
      {
        "date":"10/12/78",
        "name":"Nossa Sr.a Aparecida"
      },
      {
        "date":"11/02/78",
        "name":"Finados"
      },
      {
        "date":"11/15/78",
        "name":"Republica"
      },
      {
        "date":"12/25/78",
        "name":"Natal"
      }
    ].forEach(holiday => {
      var newHoliday = new Holiday({date: moment(holiday.date, 'MM/DD/YY').format('YYYY-MM-DD'), name: holiday.name});
      newHoliday.save();
    });
  }
});